### ISSUE TITLE
Possible missing VirtualService for the dashboard-links relation

### ISSUE THREAD

**Issue by AnotherStranger** [canonical/mlflow-operator#238]
### Bug Description

The mlflow charm fails to provide a working link to the mlflow UI in the Kubeflow dashboard. After deploying and relating the charms, the link is created but it does not work (possibly due to a missing VirtualService).
The juju debug logs only contain some warnings on a missing refresh_event (This seems to be unrelated to this report).

@kimwnasptd and I already had a short discussion in the matrix chatroom about this.

If there is anything I can do to assist you further please let me know. 

Here is a screenshot of the dashboard link which gets created after enabling the relation:
![grafik](https://github.com/canonical/mlflow-operator/assets/6563442/3b5ff04c-760a-4f80-804b-527e3bfcc107)

### To Reproduce

1. Deploy `mlflow` using channel 2.1/stable with `juju deploy mlflow --channel=2.1/stable --trust`
2. Deploy `resource-dispatcher` using channel 1.0/stable with `juju deploy resource-dispatcher --channel=1.0/stable --trust`
3. Relate the charms: `mlflow-server:pod-defaults` to `resource-dispatcher:pod-defaults`, and `mlflow-server:secrets` to `resource-dispatcher:secrets`
4. Relate the charms again: `mlflow-server:dashboard-links` to `kubeflow-dashboard:links`

### Environment

- Platform: Charmed Kubeflow using channel 1.8/stable on Microk8s
- Juju version: Channel 3.1/stable

### Relevant Log Output

```shell
application-minio: 10:06:17 WARNING unit.minio/0.juju-log 0 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
unit-metacontroller-operator-0: 10:07:13 WARNING unit.metacontroller-operator/0.juju-log 0 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
application-envoy: 10:07:18 WARNING unit.envoy/3.juju-log 0 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
unit-mlflow-server-0: 10:07:42 WARNING unit.mlflow-server/0.juju-log 2 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
application-mlflow-minio: 10:09:23 WARNING unit.mlflow-minio/0.juju-log 0 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
```

**Comment by kimwnasptd** [comment]
Thanks for opening the issue @AnotherStranger!

You could help us initially by confirming the `VirtualService` that we need to ensure the access is there, and then we can figure out how to integrate it into the Charm.

It should look very similar to the other ones, [like this one](https://github.com/kubeflow/kubeflow/blob/v1.8-branch/components/crud-web-apps/jupyter/manifests/overlays/istio/virtual-service.yaml) but change the destination to be the K8s SVC that is created for MLflow via the Charm.

Most probably we might need to play with the rewrite of the URL as well. Could you give it a spin?

**Comment by AnotherStranger** [comment]
Hey @kimwnasptd,

I got access to the mlflow app using following VirtualService (Adapted from your linked one):
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mlflow-server-mlflow-server
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /mlflow
    match:
    - uri:
        prefix: /mlflow/
    rewrite:
      uri: /
    route:
    - destination:
        host: mlflow-server
        port:
          number: 5000
```
