### ISSUE TITLE
Avoid using root user for DB connection

### ISSUE THREAD

**Issue by Barteus** [canonical/mlflow-operator#76]
The user for MySQL connection is hardcoded as root. In the same relation, a user was created called `mysql`. Using root users for connections is not a good practice.

```
    related-units:
      mlflow-db/0:
        in-scope: true
        data:
          database: database
          egress-subnets: 100.98.244.78/32
          host: 100.98.244.78
          ingress-address: 100.98.244.78
          password: password
          port: "3306"
          private-address: 100.98.244.78
          root_password: root
          user: mysql
```
https://github.com/canonical/mlflow-operator/blob/6d7b891bb3af07c460489b59803c07cd853af82f/charms/mlflow-server/src/charm.py#L370
